[package]
name = "home"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
tera = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
applicant = { path = "../applicant" }
shared = { path = "../shared" }
