[package]
name = "job"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true }
chrono = { workspace = true }
tera = { workspace = true, optional = true }
surrealdb = { workspace = true }

