CREATE event:event1 SET name = 'Developer Hiring Sprint', title='SDE1', description = 'A focused event for hiring talented developers across various tech services.', status = 'open', start_date = '2025-07-01', end_date = '2025-07-05';

CREATE event:event2 SET name = 'Product and Hiring', title='SDE2', description = 'An event focused on product development and hiring experience.', status = 'open', start_date = '2025-07-10', end_date = '2025-07-15';

CREATE event:event3 SET name = 'Tech Attend Fair', title='SDE3', description = 'A comprehensive tech fair for networking and career experiences.', status = 'closed', start_date = '2025-08-01', end_date = '2025-08-05';

CREATE event:event4 SET name = 'Engineering Week', title='SDE4', description = 'A week-long event focusing on engineering and technology Payments.', status = 'open', start_date = '2025-08-10', end_date = '2025-08-15';


