[package]
name = "serde_withs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_with = { workspace = true }
surrealdb = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
